[project]
name = "habermas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "pydantic>=2.11.9",
    "websockets>=15.0.1",
]
